# Generated by Django 4.1 on 2022-09-14 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Sport', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('court', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sport.court')),
                ('slot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sport.timeslot')),
            ],
        ),
        migrations.CreateModel(
            name='Bookslot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(null=True)),
                ('booked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('court', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sport.court')),
                ('slot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sport.timeslot')),
                ('sport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sport.sport')),
            ],
        ),
    ]
